server:
  port: 8080

eureka:
  datacenter: cloud-data-center
  environment: test
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: false
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eurekaserver/
    register-with-eureka: false #关闭自己作为客户端注册
    fetch-registry: false