server:
  port: 8080

eureka:
  instance:
  datacenter: cloud-data-center
  environment: test
    hostname: 0.0.0.0
    prefer-ip-address: false
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eurekaserver/
    register-with-eureka: false #关闭自己作为客户端注册
    fetch-registry: false
  server:
    renewal-percent-threshold: 5.1 # 2 * 3 *0.85